// Mocks generated by Mockito 5.4.6 from annotations
// in codealpha_fitness_tracker_app/test/features/route_tracking/route_tracking_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:codealpha_fitness_tracker_app/features/route_tracking/data/models/route_point.dart'
    as _i5;
import 'package:codealpha_fitness_tracker_app/features/route_tracking/data/models/route_track.dart'
    as _i4;
import 'package:codealpha_fitness_tracker_app/features/route_tracking/data/repositories/route_tracking_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RouteTrackingRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRouteTrackingRepository extends _i1.Mock
    implements _i2.RouteTrackingRepository {
  MockRouteTrackingRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.RouteTrack>> getAllRoutes() =>
      (super.noSuchMethod(
            Invocation.method(#getAllRoutes, []),
            returnValue: _i3.Future<List<_i4.RouteTrack>>.value(
              <_i4.RouteTrack>[],
            ),
          )
          as _i3.Future<List<_i4.RouteTrack>>);

  @override
  _i3.Future<void> saveRoute(_i4.RouteTrack? route) =>
      (super.noSuchMethod(
            Invocation.method(#saveRoute, [route]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteRoute(String? routeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRoute, [routeId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.RouteTrack?> getActiveRoute() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveRoute, []),
            returnValue: _i3.Future<_i4.RouteTrack?>.value(),
          )
          as _i3.Future<_i4.RouteTrack?>);

  @override
  _i3.Future<void> saveActiveRoute(_i4.RouteTrack? route) =>
      (super.noSuchMethod(
            Invocation.method(#saveActiveRoute, [route]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateActiveRoute(List<_i5.RoutePoint>? newPoints) =>
      (super.noSuchMethod(
            Invocation.method(#updateActiveRoute, [newPoints]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.RouteTrack>> getRoutesByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRoutesByDateRange, [start, end]),
            returnValue: _i3.Future<List<_i4.RouteTrack>>.value(
              <_i4.RouteTrack>[],
            ),
          )
          as _i3.Future<List<_i4.RouteTrack>>);

  @override
  _i3.Future<List<_i4.RouteTrack>> getRoutesByActivityType(
    String? activityType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getRoutesByActivityType, [activityType]),
            returnValue: _i3.Future<List<_i4.RouteTrack>>.value(
              <_i4.RouteTrack>[],
            ),
          )
          as _i3.Future<List<_i4.RouteTrack>>);

  @override
  Map<String, dynamic> calculateRouteStats(List<_i4.RouteTrack>? routes) =>
      (super.noSuchMethod(
            Invocation.method(#calculateRouteStats, [routes]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}
